services:
  common-config-initial:
    deploy:
      resources:
        limits:
          memory: 700m
    restart: always

  common-config-after-config-server:
    extends:
      service: common-config-initial
    depends_on:
      open-forum-cloud-config-server:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888/

  common-config-after-discovery-server:
    extends:
      service: common-config-after-config-server
    depends_on:
      open-forum-cloud-discovery-server:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:7777/eureka/