version: "3.8"
services:
  micro_forum_config-server:
    image: feeham/micro_forum:config-server-1.7
    container_name: config-server
    ports:
      - "8888:8888"
    extends:
      file: docker-common-configs.yml
      service: common-config-initial
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s

  micro_forum_discovery-server:
    image: feeham/micro_forum:discovery-server-1.3
    container_name: discovery-server
    ports:
      - "7777:7777"
    extends:
      file: docker-common-configs.yml
      service: common-config-after-config-server
    healthcheck:
      test: "curl --fail --silent localhost:7777/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s

  micro_forum_posts:
    image: feeham/micro_forum:posts-1.4
    container_name: posts
    ports:
      - "3100:3100"
    depends_on:
      - post-service-pg-db
    extends:
      file: docker-common-configs.yml
      service: common-config-after-discovery-server

  micro_forum_notifications:
    image: feeham/micro_forum:notifications-1.0
    container_name: notifications
    ports:
      - "3400:3400"
    extends:
      file: docker-common-configs.yml
      service: common-config-after-discovery-server

  micro_forum_gateway:
    image: feeham/micro_forum:gateway-1.0
    container_name: gateway
    ports:
      - "9999:9999"
    extends:
      file: docker-common-configs.yml
      service: common-config-after-discovery-server
